name: Production Build

on:
  workflow_run:
    workflows: ['CI']
    branches: ['main']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Prepare Deploy
        uses: ./.github/actions/prepare-deploy
        with:
          main-branch-name: main
          app-configuration: production
          nx-command: run-many
          generate-index: 'false'

      - name: Copy app to top directory
        run: |
          cp -r deploy/apps/trust-ai/* deploy
          cp deploy/index.html deploy/404.html

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
          commit_message: 'Production deploy -- ${{ github.event.head_commit.message }}'
